### ISSUE TITLE
Just installed it and getting an error

### ISSUE THREAD

**Issue by dshorowitz** [auth0-extensions/auth0-delegated-administration-extension#1]
I just installed this extension and am very excited about it! However, after logging in, I'm getting the following error:

![image](https://cloud.githubusercontent.com/assets/11761476/17939484/df735620-69f8-11e6-9190-25e091a5a2b7.png)

Any ideas about where to start debugging this?

**Comment by sandrinodimattia** [comment]
Could you install the Realtime Logs extension. This will show you what's happening and why it fails. It would be useful if you could paste the details of the error here.

**Comment by dshorowitz** [comment]
Sure. Here's the output:

`:13:07 PM: 2016-08-24T21:13:07.279Z - error:  ManagementApiError: Invalid credentials for XXXXXXX
    at /data/YYYYYYYYYYYY:1:12107
    at Request.callback (/data/_verquire/superagent/1.2.0/node_modules/superagent/lib/node/index.js:797:3)
    at IncomingMessage.<anonymous> (/data/_verquire/superagent/1.2.0/node_modules/superagent/lib/node/index.js:990:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)`

**Comment by sandrinodimattia** [comment]
Ah. Could it be that you deleted the `auth0-delegated-admin` client?

**Comment by dshorowitz** [comment]
Hmm, the client is still there. I just double checked and the Client ID for the auth0-delegated-admin client matches the Client ID in the extension settings.

**Comment by sandrinodimattia** [comment]
Here's how my account is setup:

![image](https://cloud.githubusercontent.com/assets/655409/17948597/4e4fa9e2-6a06-11e6-8213-083fcb1fe40a.png)

As you can see, there's 2 Clients. The first one is the one I manually created before installing the extension as explained here: https://auth0.com/docs/extensions/delegated-admin#configure-the-extension. This is the client which secures the extension itself. When users login, this client will be used to show the Lock etc...

When you install the extension, this is the Client ID you have to enter here:

![image](https://cloud.githubusercontent.com/assets/655409/17948869/9c4b8066-6a07-11e6-9fd5-f4b842efb08a.png)

The second client `auth0-delegated-admin` is a Client for the Management API. This one is created automatically when installing the extension and is authorized to access the Management API.

Did you make any changes to the first client? And is your account setup like this?

**Comment by dshorowitz** [comment]
It works! Thanks for the help. The confusion stemmed from the auto-created client (I had deleted it, not recognizing what it was). You might want to update the docs to indicate that it will be auto created?

Is there any way to limit the users returned to the dashboard by arbitrary criteria (like connection, for example)?

**Comment by sandrinodimattia** [comment]
Released v2.0 (to limit users etc...) and updated docs to cover this feature + the auto created client: https://auth0.com/docs/extensions/delegated-admin
