### ISSUE TITLE
User Information shows all available Memberships as opposed to User's one only

### ISSUE THREAD

**Issue by abbaspour** [auth0-extensions/auth0-delegated-administration-extension#109]
Under `User Information` > `Memberships` lists all available memberships irrespective ones this user is a member of: 

![dae-v2-membership-hook](https://user-images.githubusercontent.com/68219/43371656-e0408296-93d9-11e8-9e3f-d4fe224a2004.png)
![dae-v3-profile](https://user-images.githubusercontent.com/68219/43371657-e06cfb28-93d9-11e8-8ba0-b7a0d198bba7.png)
![dae-v3-user-info](https://user-images.githubusercontent.com/68219/43371658-e0a31f46-93d9-11e8-8c76-9b085c7f0436.png)

**Comment by shawnmclean** [comment]
Hi @abbaspour, if you are still having this issue, feel free to re-open.
