### ISSUE TITLE
If an action is restricted via access hook hide it from the actions drop down

### ISSUE THREAD

**Issue by pushpabrol** [auth0-extensions/auth0-delegated-administration-extension#115]
DAE still shows an option for an action in the actions drop down even if the user is not allowed to do it. For example, If change:password is restricted It should not even show that as an option on the UI. Showing the option and then showing an error after a user attempts that operation is not a good user experience.

**Comment by shawnmclean** [comment]
Fixed  in https://github.com/auth0-extensions/auth0-delegated-administration-extension/releases/tag/v3.2.0
