### ISSUE TITLE
Logs show `Unknown Error` for "Success Exchange (Password for Access Token)"

### ISSUE THREAD

**Issue by simon-weiser23** [auth0-extensions/auth0-delegated-administration-extension#148]
The logType `sepft` (Type = Success Exchange, Description = Password for Access Token) is shown as `Unknown Error` in the logs of a user detail view. In the logs of the Auth0 tenant itself at [https://manage.auth0.com/#/logs](https://manage.auth0.com/#/logs) the same event is shown as `Success Exchange` with the description `Password for Access Token`. When investigating this issue it got to our attention that the file [logTypes.js](https://github.com/auth0-extensions/auth0-delegated-administration-extension/blob/master/client/utils/logTypes.js) does not include the `sepft` event. This may be the reason for not being mapped correctly and ending up in the default case as `Unknown Error`.

**Comment by simon-weiser23** [comment]
The same goes for the `sertft`event (Type = Success Exchange, Description = Refresh Token for Access Token).

**Comment by simonweiser** [comment]
Any news regarding this issue?

**Comment by fyockm** [comment]
@simon-weiser23 the update for this was just released as [`3.4.5`](https://github.com/auth0-extensions/auth0-delegated-administration-extension/releases/tag/v3.4.5)
