### ISSUE TITLE
Configuration - Membership Hook inconsistent description

### ISSUE THREAD

**Issue by bastula** [auth0-extensions/auth0-delegated-administration-extension#153]
https://github.com/auth0-extensions/auth0-delegated-administration-extension/blob/3fe952c296096b05972f81f42aaed60f5fd6c2b3/client/containers/Configuration/Configuration.jsx#L161

In the Membership Hook configuration, the tab is referred to as Memberships **Hook**, but the copy states **Query** instead of **Hook**. Likewise for the save button.

**Comment by bastula** [comment]
Can this copy be updated?

**Comment by fyockm** [comment]
@bastula would you mind submitting a simple PR for this?

**Comment by bastula** [comment]
I don't mind, I just wasn't sure which way you guys want to go with the terminology?
