### ISSUE TITLE
Reset Password requires client selection

### ISSUE THREAD

**Issue by bastula** [auth0-extensions/auth0-delegated-administration-extension#154]
When entering the Reset Password UI for a user, a required field for the application client is shown. Is this exposing unintended application client names to the user?

I am using the version 3.4 of the extension in the US.

<img width="637" alt="screen shot 2018-12-13 at 2 50 53 pm" src="https://user-images.githubusercontent.com/61406/49966779-99bc7c80-fee6-11e8-814c-24c123102b88.png">

**Comment by bastula** [comment]
Hi @zxan1285,

I understand that it will be used for the email provider. Is there a way to default the dropdown (or make it a fixed value) if we are trying to deliver the delegated administration to customers? I am not sure if they would know what to pick.

**Comment by zxan1285** [comment]
You can use `Settings Query` for that - https://auth0.com/docs/extensions/delegated-admin/v3/hooks/settings#custom-fields
Like this:
```
userFields: [
    {
        "property": "client",
        "label": "Client",
        "search": false,
        "edit": {
            "display": true,
            "type": "select",
            "component": "InputSelectCombo",
            "options": [{ "value": "[client_id]", "label": "[client_name]" }],
            "required": true
        },
        "create": false
    },
    ...
]
```

**Comment by fyockm** [comment]
@bastula did this answer your question?

**Comment by bastula** [comment]
@fyockm It does, but I could not make it work as when I put in my `client_id` and `client_name` the form did not submit properly.

I think the main point is that the client field was not documented that it is able to be overridden.
