### ISSUE TITLE
Allow direct metadata editing

### ISSUE THREAD

**Issue by dmark** [auth0-extensions/auth0-delegated-administration-extension#161]
Allow direct editing of `user_metadata` and `app_metadata` (similar to the management console), ideally through role-based access control measures (additional roles for user and app metadata editing).

Obviously direct editing is error prone and should only be used by properly trained and experienced support staff, but it is a requirement for us. We have a few senior support staff who have access to the entire management console just so they can edit metadata. We have a stalled project to build our own equivalent of the DA dashboard with metadata editing capabilities, but it would be great if the extension supported it natively.

**Comment by bondrap** [comment]
I am also interested in this. I would like for Administrator to be able to edit user meta_data.
