### ISSUE TITLE
Add support for new Auth0 RBAC features

### ISSUE THREAD

**Issue by twistedstream** [auth0-extensions/auth0-delegated-administration-extension#170]
This feature would involve two changes:

## Controlling access to the DAE dashboard
First, instead of driving access to the DAE dashboard via an ID Token with a custom "roles" claim, use an OAuth Access token that carries the required permissions. 

Some considerations:

* This would require that a custom "Delegated Admin" API is also configured in Auth0. Not sure if the user should create this ahead of time and configure its `identifier` value in the extension configuration variables on creation or if the extension can simply create it.
* At a minimum, the API would need to define permissions that map to the four existing DAE "roles": `User`, `Administrator`, `Auditor`, `Operator` so the dashboard behavior can be driven accordingly.
   * **NOTE:** We should strive to make the DAE be permission-based (vs. role based) so that admins can define their own roles in Auth0 that map to these permissions, just like they would with other custom APIs they define.
* We need to decide how to transmit permissions in the access token. Either via the `scope` claim or `permissions` claim (if the **Add Permissions in the Access Token** flag is true for the API). It might be simpler to only use the later since the DAE wouldn't need to request scopes in the `/authorize` call.

## Support RBAC role assignment of managed users

Currently, the DAE only allows updates of a user's profile (eg. `user_metadata` and `app_metadata`). But for proper RBAC support, we'd need a way for the hooks to be instructed to set a user's RBAC roles, which is done external to their profile. It seems like we could provide an option for the "membership" capability to simply leverage the RBAC roles defined in the tenant. However, the `Memberships Hook` will still be important to filter the possible list of roles a given admin can assign. Likewise, the `Write Hook` will need to enforce this.

**Comment by ncknuna** [comment]
First of all, thanks for making a great platform! 

Question: Is there a timeline for this work? I need functionality like this and if this won't be done for a while I'll unfortunately have to roll my own

**Comment by rickenberg** [comment]
I find this very relevant, too. Especially the second part regarding the role assignment of managed users. Do you have any plans on adding RBAC support to the delegated admin extension? Or could you provide some more tech details so that we could implement it ourselves?

**Comment by bastula** [comment]
I ended up using the provided hooks and the Auth0 management API to implement this. You still can't edit a user's membership (Role in this case) after they have been created, only upon creation. This is due to a limitation in this extension. However, other than that issue it works fine.

**Comment by rhadsallarch** [comment]
Why aren't there any responses from auth0?
