### ISSUE TITLE
Update docs to fully explain rules-based authorization via ID Token custom claim

### ISSUE THREAD

**Issue by twistedstream** [auth0-extensions/auth0-delegated-administration-extension#175]
This [section in the docs](https://auth0.com/docs/extensions/delegated-admin/v3#assign-roles-to-users) explains how to configure authorization in your Auth0 tenant so the right users have access to the DAE dashboard. The basic approach being:
1. You need to configure your SPA client so that it sends the entire user profile by disabling the `OIDC Confirmant` flag and configuring the `Allowed APPs / APIs` field under the app's advanced settings
2. Configure each admin user such that they have the expected roles in a `roles` or `authorization.roles` property of their `app_metadata`

I think there used to be an older rule sample that showed how to dynamically assign these roles in the `user.app_metadata` based on other inputs (like `app_metadata.department`) in the login transaction (so they didn't have to be persisted to the user profile).

However, the current [rule sample](https://auth0.com/docs/extensions/delegated-admin/v3#set-user-roles-via-rules) shows a very _different_ approach. This sample has you configuring the response's ID Token with a custom claim that carries the role values. Therefore the extension SPA is able to read role data from either the `app_metadata` or a custom claim in the ID Token.

Using a custom claim in the ID Token approach has a huge benefit:
**You DO NOT need to configure the DAE SPA app per step 1 above, which is more secure**

Unfortunately, the docs don't point this out, nor do they really explain the difference between the two approaches.

They also don't explain the constraints that the SPA is looking for when looking for this custom claim. The example rule has the following claim name:
`https://example.com/auth0-delegated-admin`
If someone wants to use their own claim name, it must follow these rules:
* The claim name must start with `https://`
* The claim name must end in `/auth0-delegated-admin`

IMO we should rewrite this docs page a bit to explain the above and really make the custom claim in the ID Token approach the default recommended approach, leaving the old approach as a legacy behavior.

**Comment by zxan1285** [comment]
IIRC, starting with v3 the extension is requesting user data from API2 to get `app_metadata`. That part of the docs (about OIDC and allowed APIs) is outdated. Regular SPA without additional configuration (except `Allowed Callback URLs`) will work fine for both `app_metadata` and custom claim added in the rule.
