### ISSUE TITLE
Extension customization/clone

### ISSUE THREAD

**Issue by lomboboo** [auth0-extensions/auth0-delegated-administration-extension#187]
Hello,

I would like to make a clone of Delegated Administration Dashboard extension to be able to customize it for my needs. I created new public project on github.
The problem is, when I change only extension name (to not conflict with existing one) and try to install extension in the Auth0 Dashboard, it appears in the installed extensions tab and when I click on it redirects to extension url with json error:

```
{ 
"code": 400, 
"message": "Compilation failed: Cannot find module './server/lib/logger'", 
"error": "Cannot find module './server/lib/logger'", 
"stack": "Error: Cannot find module './server/lib/logger'\n at Function.Module._resolveFilename (module.js:547:15)\n at Function.WebtaskModule._resolveFilename (/data/sandbox/lib/module.js:56:27)\n at WebtaskModule.require (/data/sandbox/lib/module.js:149:39)\n at require (/data/sandbox/lib/module.js:184:21)\n at Object.<anonymous> (/data/io/ed680379-e817-4d61-9a4e-900272dd7736/webtask.js:3:16)\n at WebtaskModule.compileWebtask (/data/sandbox/lib/module.js:143:34)\n at defaultJavascriptCompiler (/data/sandbox/lib/compiler.js:119:30)\n at defaultCompiler (/data/sandbox/lib/compiler.js:128:16)\n at /data/sandbox/lib/compiler.js:231:17\n at /data/sandbox/node_modules/async/dist/async.js:3880:24"
}
```

Are there any additional dependencies/steps needed to build extension from source (clone)?

**Comment by zxan1285** [comment]
Hi!

To install the extension as custom, you have to build it (`npm run build`), commit `dist/**.extension.js` file to the repo and then add raw github url to that file in `webtask.json` (`"codeUrl": "https://raw.githubusercontent.com/..."`).

Also, you need to host your UI files somewhere and change `cdnPath` here https://github.com/lomboboo/auth0-delegated-administration-extension/blob/master/server/routes/html.js#L94

**Comment by lomboboo** [comment]
@zxan1285 
So I ran build, comitted **manage-users.extension.3.7.0.js** to repo, added 
`"codeUrl": "https://raw.githubusercontent.com/lomboboo/auth0-delegated-administration-extension/master/dist/manage-users.extension.3.7.0.js"` to the **webtask.json**, but still get the same error as in my question after extension install.

**Comment by zxan1285** [comment]
@lomboboo try using direct link to the `webtask.json` (https://raw.githubusercontent.com/lomboboo/auth0-delegated-administration-extension/master/webtask.json) when installing the extension.

**Comment by lomboboo** [comment]
> @lomboboo try using direct link to the `webtask.json` (https://raw.githubusercontent.com/lomboboo/auth0-delegated-administration-extension/master/webtask.json) when installing the extension.

Thanks, yes, it seems to be working, however docs are not clear about what you described. It would be nice to have precise steps documented somewhere
