### ISSUE TITLE
Verfication Email after changing password

### ISSUE THREAD

**Issue by Wrixst** [auth0-extensions/auth0-delegated-administration-extension#194]
If I change the users password by pressing the action button in the delegated admin dashboard there is no verification Email send to the user. I have to send it by pressing the button "send verification email". I would expect that the verification email is send automaticly or at leased I would be ask by the system if it should be send.

the behaviour is the same on the admin dashboard.

**Comment by aarongodin** [comment]
Hey @Wrixst, I'm trying to follow why it's useful to verify the user's email again when it hasn't changed. To clarify, you're changing the password yourself and not using the Reset Password action?

Also as you noted, this behavior is the same in the main dashboard. If there is a case to change the behavior, we will want to review the functionality there as well.

**Comment by Wrixst** [comment]
Hy Aaron,

sorry, mayby I didn´t express myself right. In my Opinion if there is a change of Emailadress or a change of PWD made my the Administrator or someone else usiung the main Dashboard or the delegated Admin Dasboard, there should the a notification to the customer. In Case of changing the EmailAdress, a Email to the old Emailadress and in case of changing PWD to the emailadress. It would help a customer to find out that mayby someone is trying to take over his account.

Thanx

Mark



Von: Aaron Godin <notifications@github.com>
Gesendet: Donnerstag, 20. Februar 2020 23:25
An: auth0-extensions/auth0-delegated-administration-extension <auth0-delegated-administration-extension@noreply.github.com>
Cc: Düsenberg Mark <m.duesenberg@enbw.com>; Mention <mention@noreply.github.com>
Betreff: Re: [auth0-extensions/auth0-delegated-administration-extension] Verfication Email after changing password (#194)


Hey @Wrixst<https://github.com/Wrixst>, I'm trying to follow why it's useful to verify the user's email again when it hasn't changed. To clarify, you're changing the password yourself and not using the Reset Password action?

Also as you noted, this behavior is the same in the main dashboard. If there is a case to change the behavior, we will want to review the functionality there as well.

**Comment by Wrixst** [comment]
Still open

**Comment by hous** [comment]
Hi Mark,

Thanks for your feedback, but we won't be updating this behavior. An administrative action taken by an administrator doesn't represent someone "taking over the account". The administrator can always contact the user if needed.

Thanks,

Adam
