### ISSUE TITLE
User Name is not changed after changing Email

### ISSUE THREAD

**Issue by Wrixst** [auth0-extensions/auth0-delegated-administration-extension#195]
If I change the users Email by using the Delegated Admin Dashboard, the previous set Name (Old Email) is not changed to the new one. This is confusing because in the userlist you see the old Email and below you can see the new one. I would expect that the name would also be changed.

The behaviour is the same on the Admin Dashboard.

**Comment by aarongodin** [comment]
Thanks for opening an issue for this. FYI - we need to review the usage of the `stale` bot as it's inaccurate that we won't fix this :)

I've seen this issue in the main dashboard as well. I agree it's confusing and we should work to understand how to improve this. I've logged a note internally with another team that works on the user management portions of the dashboard. I'd like to understand if they have others asking for this to be less confusing.

**Comment by Wrixst** [comment]
Thanx

Von: Aaron Godin <notifications@github.com>
Gesendet: Donnerstag, 20. Februar 2020 23:28
An: auth0-extensions/auth0-delegated-administration-extension <auth0-delegated-administration-extension@noreply.github.com>
Cc: Düsenberg Mark <m.duesenberg@enbw.com>; Author <author@noreply.github.com>
Betreff: Re: [auth0-extensions/auth0-delegated-administration-extension] User Name is not changed after changing Email (#195)


Thanks for opening an issue for this. FYI - we need to review the usage of the stale bot as it's inaccurate that we won't fix this :)

I've seen this issue in the main dashboard as well. I agree it's confusing and we should work to understand how to improve this. I've logged a note internally with another team that works on the user management portions of the dashboard. I'd like to understand if they have others asking for this to be less confusing.

**Comment by Wrixst** [comment]
still open

**Comment by Wrixst** [comment]
will open

**Comment by Wrixst** [comment]
Still open
