### ISSUE TITLE
Select component for creating users overflows display

### ISSUE THREAD

**Issue by nicosabena** [auth0-extensions/auth0-delegated-administration-extension#201]
When creating an edit field of type "select", if the number of options is large it overflows the popup windows and users can't select the bottom options.
To reproduce, use this **Settings Query** hook:

```js
function(ctx, callback) {
  return callback(null, {
    userFields: [
      {
        property: "property1"
        create: {
          type: "select",
          component: "InputSelectCombo",
          options: [
            "Option1", "Option2", "Option3", "Option4", "Option5", "Option6", "Option7", "Option8", "Option9"
          ]
        }
      }
    ]
  });
};
```

and you get this:
![image](https://user-images.githubusercontent.com/5222181/70478754-aee3d100-1a90-11ea-9ec4-32321533d9ed.png)

Neither the keyboard nor the mouse lets you get to the last options.

**Comment by ubenzer** [comment]
The fix is deployed and verified on Delegated Admin Extension 3.7.2 on Chrome.
