### ISSUE TITLE
Configuration option for custom authentication domain unavailable

### ISSUE THREAD

**Issue by borrell** [auth0-extensions/auth0-delegated-administration-extension#208]
In the initial extension configuration, there has previously been an option to configure a custom auth domain. This isn't available in the most recent version, causing existing configurations with external IdP systems to break when reinstalling the extension.

<img width="608" alt="Screen Shot 2020-01-25 at 11 51 32 AM" src="https://user-images.githubusercontent.com/183934/73124432-724d3580-3f69-11ea-8ba2-d3fc0bd30942.png">

**Comment by yacineMTB** [comment]
Hey @borrell, thanks for raising this. We've fixed the issue: on reinstalling the extension you should be able to see the custom domain option.
