### ISSUE TITLE
Improve the logout flow

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0-extensions/auth0-delegated-administration-extension#48]
Logout should:

 - Clear any local state
 - Redirect to the logout endpoint in Auth0
 - Send the user back to the extension

**Comment by saltukalakus** [comment]
Tested with an ADFS user and after logout user can login without re-entering the credentials for the ADFS connection. Expected behaviour is to log in again to ADFS connection. P1 ZD #22964

**Comment by sandrinodimattia** [comment]
This has been implemented and released as 2.4.3
