### ISSUE TITLE
"Unknown Event" in Logs

### ISSUE THREAD

**Issue by marco-jantke** [auth0-extensions/auth0-delegated-administration-extension#58]
I recently setup this Extension in our Auth0 account. One use case of us for this extension, is the ability to enable viewing of the Logs for a certain user group of our staff. Anyway, after installing and trying it out, I realised that most of the Logs from other Clients are shown as "Unknown Event" and therefore breaks our use case.

Can you point out a bit why this is happening and whether maybe we only miss some configuration for that? If there is a way to make that working and it is just missing some code functionality can you please give some hint to where and how it should be implemented? It is an option for us to extend the functionality on our own and to create a PR for that.

After some more checking I figured out that there is also the same for "Unknown Error". Just to make it sure, in the Auth0 Dashboard I can see the proper error messages etc.

**Comment by CalRobert** [comment]
Investigating this and I can't seem to reproduce. Obviously this issue is quite old, but if anyone else encountering this can share steps to reproduce (maybe the app and user settings for the delegated app, for instance) that would be helpful.

**Comment by shawnmclean** [comment]
Thanks @CalRobert for looking into it. Closing. @marco-jantke if you still have this issue, please feel free to re-open.
