### ISSUE TITLE
No paging in the Users list

### ISSUE THREAD

**Issue by bswaugh** [auth0-extensions/auth0-delegated-administration-extension#60]
The Users list only displays a maximum of 100 users. Could there be a paging mechanism at the bottom?
Also, if the User Management page in the main dashboard shows 10 users at a time, could the Deleated Admin dashboard also show 10 users per page?

**Comment by saltukalakus** [comment]
P1 ZD - 23056, After 100 users there is no way to list reset of the users.

<img width="1115" alt="screen shot 2017-05-06 at 01 27 57" src="https://cloud.githubusercontent.com/assets/815705/25766507/a1f38ac4-31fb-11e7-9668-80007378d0f3.png">

**Comment by francocorreasosa** [comment]
Working on this right now. 😄

**Comment by sandrinodimattia** [comment]
This is now available in the latest release.

**Comment by bswaugh** [comment]
I updated to 2.4 and now it is broken.

**Comment by saltukalakus** [comment]
@bswaugh yesterday there was a short outage in extensions affecting all extensions including the delegation extension. Could you retest now. https://status.auth0.com/incidents/v43m9549b1j4

**Comment by bswaugh** [comment]
I am still seeing the same error on the Users page.
