### ISSUE TITLE
Custom domain?

### ISSUE THREAD

**Issue by rsteckler** [auth0-extensions/auth0-delegated-administration-extension#61]
I'm currently running the built in auth0 delegated administration extension, but I want a custom domain.  Is this codebase the same extension?  Do I just run this on my own server and hook it up via the client Id and secret from my auth0 account?

**Comment by sandrinodimattia** [comment]
Yes, this is the same codebase, so you should be able to just deploy it to Heroku for example.

Here's the command to run: https://github.com/auth0-extensions/auth0-delegated-administration-extension/blob/master/package.json#L15

The extensions platform will automatically provision a non-interactive client (for accessing API v2) upon installation. If you deploy this yourself, you will need to create a client with the proper permissions: https://github.com/auth0-extensions/auth0-delegated-administration-extension/blob/master/webtask.json#L21
