### ISSUE TITLE
Sorry, you have no permissions to do this.

### ISSUE THREAD

**Issue by svanbelleghem** [auth0-extensions/auth0-delegated-administration-extension#65]
Followed the instructions on the auth0 page but keep getting the error:

```
Oh snap! You got an error!

An error occurred while retrieving list of users: Forbidden! Sorry, you have no permissions to do this.
```

I created and tested my own rule which adds the correct roles to a user. 

```
function (user, context, callback) {
  if (context.clientID === 'xx') {
    if (user.email === 'xx' || user.email === 'xx') {
      context.idToken.roles = ['admin', 'guest'];
    
      user.roles = user.roles || [ ];
      user.roles.push('Delegated Admin - Administrator');
      return callback(null, user, context);
    } else {
        context.idToken.roles = ['guest'];
    }
    
    return callback(new UnauthorizedError('You are not allowed to use this application.'));
  }
  callback(null, user, context);
}
```

**Comment by omar** [comment]
Have the same issue. I tried and retried following the tutorial exactly on two different tenants with the same issue.

I even copied the `getScope` code (in `server/lib/getScopes.js`), supplied it the following user (which I copied directly from the Auth0 user details page), and received the correct scope but still getting the error.

I think there might be a problem with how it's setup in the cloud version of the extension. Using version 2.5. The error message we're seeing is not in the source code which leads me to believe it's being bubbled up from another API call. Maybe from a failed connection to the management API?

```
import getScopes from './getScopes';

let user =   {
    "email": "user-email@email.com",
    "email_verified": false,
    "user_id": "auth0|5a8c38f5f5c8213cb27d35b5",
    "picture": null,
    "nickname": "okhudeira",
    "identities": [
        {
            "user_id": "5a8c38f5f5c8213cb27d35b5",
            "provider": "auth0",
            "connection": "Helpdesk",
            "isSocial": false
        }
    ],
    "updated_at": "2018-02-20T15:04:57.274Z",
    "created_at": "2018-02-20T15:04:21.268Z",
    "user_metadata": {},
    "name": "User Name",
    "app_metadata": {
        "roles": [
            "Delegated Admin - Administrator"
        ]
    },
    "last_ip": "162.17.51.157",
    "last_login": "2018-02-20T15:04:57.274Z",
    "logins_count": 2,
    "blocked_for": [],
    "guardian_authenticators": []
};

console.log(getScopes(user)); // Outputs "[ 'manage:users', 'manage:config' ]"
```

**Comment by omar** [comment]
I contact Auth0 support and the acknowledged that the issue is from their end. They revert a setting on my tenant to allow me to use the older version of the extension and let me know that they're working on fixing it for all users. 

After they made the change, I was able to use the extension.

**Comment by edgurgel** [comment]
@omar do you know which version are you using right now?

**Comment by abbaspour** [comment]
For versions below 3 (2.5, 2.6) you need to enable Legacy User Profile.
Go to Dashboard > Tenant Settings > Advanced > Migrations > Legacy User Profile

![screen shot 2018-06-13 at 12 27 07 pm](https://user-images.githubusercontent.com/68219/41327087-6c4d817a-6f05-11e8-9cee-47f8a3b67565.png)

**Comment by peterholdsworth** [comment]
If you are using Auth0 Authorization to assign the `Delegated Admin - User` and `Delegated Admin - Admin` roles then make sure that Roles are persisted:
![screen shot 2018-07-11 at 08 33 14](https://user-images.githubusercontent.com/2823542/42557054-56d17d56-84e5-11e8-8391-41345365e47a.png)
