### ISSUE TITLE
Bug writing hooks

### ISSUE THREAD

**Issue by alexcarruthers** [auth0-extensions/auth0-delegated-administration-extension#66]
When I write a hook, even a stupidly simple one like:
```
function(ctx, callback) {
  return callback();
}
```
I get the following error in the UI: 
![screen shot 2017-06-09 at 10 17 36 am](https://user-images.githubusercontent.com/2522177/26979478-e9933d4a-4cfc-11e7-8c3e-19bb28e1ea3f.png)

It seems to happen no matter which hook I set up.

Is there a bug somewhere?

**Comment by sandrinodimattia** [comment]
Hi @alexcarruthers we were able to find the issue and applied a fix. This was related to changes in `babel` related to the dynamic usage of `require`. Using an external library (eg: `require-like`) which is not touched by babel solved the issue.
