### ISSUE TITLE
Fails with OIDC Conformant set to true

### ISSUE THREAD

**Issue by stevezau** [auth0-extensions/auth0-delegated-administration-extension#76]
When setting the Delegated Admin client to OIDC Conformant it fails to login. The login is successful as per Auth0 logs but the application flicks you back to the login screen.

OIDC Conformant is now on by default which means this extension should probably follow the OIDC spec.

**Comment by mpaktiti** [comment]
We updated the docs to reflect this https://github.com/auth0/docs/pull/5048
